org.gradle.java.home=C:/Program Files/Microsoft/jdk-21.0.12.101-hotspot
org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=512m
kotlin.incremental=false
android.overridePathCheck=true
android.useAndroidX=true
android.enableJetifier=true
android.builtInKotlin=false
android.newDsl=false
